const panel=document.getElementById('connect-app');
const announce=text=>document.getElementById('connect-status').textContent=text;
const model={step:'receive',identity:null,fixture:null,error:null,submitted:false,generation:0};
const embedded=new URLSearchParams(location.search).get('embedded')==='1';
if(new URLSearchParams(location.search).get('mobile')==='1')document.body.classList.add('mobile');
function render(focus){
 if(model.step==='receive')panel.innerHTML=`<p class="connect-step">01 / RECEIVE</p><h2>No second phone.<br>No camera shuffle.</h2><p class="footnote">Choose the QR image already on this device. It is decoded here; nothing is uploaded.</p><div class="qr-object"><h3>An invitation, within reach.</h3><img src="connect-captures/demo-sam-qr.png" alt="Scannable demo QR, not a real SimpleX invitation"><small>Demo QR · no working connection credentials</small></div><div class="source-buttons"><label class="file-label">Read a QR image<input type="file" id="qr-file" accept="image/png,image/jpeg,image/webp" aria-label="Choose QR image from this phone"></label><button id="read-demo">Try the demo image</button></div><p class="footnote">Future native entry: select an image → Share → SimpleX. The same connection sheet unfolds. No background gallery or clipboard access.</p><div class="fixture-links"><a href="connect-captures/demo-sam-qr.png" download="demo-sam-qr.png">Save demo QR</a><a href="connect-captures/demo-own-qr.png" download="demo-own-qr.png">Own-link test</a><a href="connect-captures/demo-used-qr.png" download="demo-used-qr.png">Used-link test</a></div>`;
 else if(model.step==='decoding')panel.innerHTML='<p class="connect-step">LOCAL READING</p><h2>Reading this image.</h2><p class="footnote">No network lookup or connection is happening.</p><button id="cancel-connect">Cancel</button>';
 else if(model.step==='found')panel.innerHTML=`<p class="connect-step">02 / READ</p><h2>The QR becomes<br>a connection doorway.</h2><div class="connect-review"><h3>Demo invitation detected.</h3><p>No recipient profile has been looked up yet.</p><p class="small">Image decoding was local. This is a one-time demo fixture, not a permanent personal ID.</p></div><p class="warning">In the proposed native flow, continuing may retrieve and lock a one-time invitation. It is not a background preview. This demo makes no request.</p><button id="read-invitation" class="primary" style="width:100%">Continue with demo invitation</button><button id="cancel-connect" class="connect-cancel">Cancel</button>`;
 else if(model.step==='review')panel.innerHTML=`<p class="connect-step">03 / CONNECT</p><h2>Choose what<br>Sam sees.</h2><div class="connect-review"><span class="mark" aria-hidden="true">S</span><h3>Sam · demo profile</h3><p class="small">Recognised name does not verify the person. Confirm independently when needed.</p></div><div class="identity-choices" role="group" aria-label="Identity to share"><button data-identity="Austin" aria-pressed="${model.identity==='Austin'}">Austin</button><button data-identity="River Finch" aria-pressed="${model.identity==='River Finch'}">Incognito</button></div><p class="footnote">${model.identity?'Sam would see: '+model.identity+'.':'Choose an identity. None is preselected.'}</p><button id="simulate-connect" class="primary" style="width:100%" ${!model.identity?'disabled':''}>Simulate connection</button><button id="cancel-connect" class="connect-cancel">Cancel connection</button>`;
 else if(model.step==='pending')panel.innerHTML=`<p class="connect-step">SIMULATED REQUEST</p><h2>Your identity<br>has been chosen.</h2><div class="pending-mark">As ${model.identity}</div><p class="footnote">The request is simulated once. No real connection or verified identity is claimed.</p><button id="finish-demo" class="primary" style="width:100%">Finish the demo connection</button>`;
 else if(model.step==='done')panel.innerHTML=`<p class="connect-step">DEMO CONNECTION READY</p><h2>Sam is within reach.</h2><div class="connect-review"><span class="mark" aria-hidden="true">S</span><h3>Sam</h3><p>As ${model.identity} · not identity verified</p><p class="small">No messages or real credentials were exchanged.</p></div><div class="success-actions">${embedded?'<button id="return-to-task" class="primary">Return to your people</button>':'<a href="intent.html?mobile=1">Explore Pause → Resume</a>'}<button id="reset-connect">Try another demo</button></div>`;
 else panel.innerHTML=`<p class="connect-step">NOT CONNECTED</p><h2>Keep the choice<br>in your hands.</h2><div class="error-box" role="alert">${model.error}</div><button id="reset-connect" class="primary">Choose another image</button><p class="footnote">No URL was opened, no profile was shared, and no invitation was fetched.</p>`;
 document.getElementById('connect-back').disabled=model.step==='receive'||model.step==='pending';
 if(focus)document.getElementById(focus)?.focus({preventScroll:true});panel.scrollTop=0;
}
function reject(text){model.error=text;model.step='error';model.fixture=null;render('reset-connect');announce(text);}
async function decode(file){
 const generation=++model.generation;model.identity=null;model.fixture=null;model.submitted=false;
 if(!file||file.size>4*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type)){reject('Choose a PNG, JPEG or WebP image under 4 MB.');return;}
 model.step='decoding';render('cancel-connect');let bitmap;
 try{bitmap=await createImageBitmap(file);if(generation!==model.generation)return;if(bitmap.width*bitmap.height>16000000)throw Error('large');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height);const code=window.jsQR(pixels.data,pixels.width,pixels.height);if(generation!==model.generation)return;
 if(!code){reject('No readable QR found. Try a clearer image containing one code.');return;}
 // Only deliberately non-operational fixture tokens enter the simulation.
 if(code.data==='sx-design-demo:invite:own'){reject('This fixture is your own invitation. Choose an invitation from someone else.');return;}
 if(code.data==='sx-design-demo:invite:used'){reject('This demo invitation is marked unavailable. Ask for a new invitation; do not auto-retry.');return;}
 if(code.data!=='sx-design-demo:invite:sam'){reject('This QR is outside the demo. Real links are not opened or retained here. Use the actual SimpleX app.');return;}
 model.fixture='sam';model.step='found';render('read-invitation');announce('Demo invitation decoded locally. Nothing connected.');
 }catch{if(generation===model.generation)reject('This image could not be read. Choose a supported image under 4 MB and 16 megapixels.');}finally{bitmap?.close();}
}
panel.addEventListener('change',e=>{if(e.target.id==='qr-file')decode(e.target.files?.[0]);});
panel.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b||b.disabled)return;
 if(b.id==='read-demo'){const generation=++model.generation;model.step='decoding';render('cancel-connect');try{const response=await fetch('connect-captures/demo-sam-qr.png');const blob=await response.blob();if(generation===model.generation)decode(new File([blob],'demo.png',{type:'image/png'}));}catch{if(generation===model.generation)reject('The demo image could not load. Choose a QR image instead.');}}
 else if(b.id==='read-invitation'){model.step='review';render('cancel-connect');announce('Demo profile read. Choose your identity before connecting.');}
 else if(b.dataset.identity){model.identity=b.dataset.identity;render();panel.querySelector('[data-identity="'+model.identity+'"]').focus({preventScroll:true});}
 else if(b.id==='simulate-connect'){if(model.submitted||!model.identity)return;model.submitted=true;model.step='pending';render('finish-demo');announce('One connection request simulated. Identity choice is fixed for this request.');}
 else if(b.id==='finish-demo'){model.step='done';render(embedded?'return-to-task':'reset-connect');announce('Demo connection ready. Identity is not verified.');}
 else if(b.id==='return-to-task'){parent.postMessage({type:'design-demo-connected',identity:model.identity},location.origin);}
 else if(['cancel-connect','reset-connect'].includes(b.id)){model.generation++;model.identity=null;model.fixture=null;model.submitted=false;model.step='receive';render('read-demo');announce('Connection preparation cleared. Nothing connected.');}
});
document.getElementById('connect-back').addEventListener('click',()=>{model.generation++;if(model.step==='review'){model.identity=null;model.step='found';render('read-invitation');}else{model.identity=null;model.submitted=false;model.step='receive';render('read-demo');}});
render();
