const app=document.querySelector('#app');
const say=text=>document.querySelector('#announcement').textContent=text;
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(new URLSearchParams(location.search).get('mobile')==='1')document.body.classList.add('mobile');
const people={maya:{name:'Maya',kind:'Person · private chat',type:'person',mark:'M',message:'Shall we meet on Saturday?'},family:{name:'Family',kind:'Private group · four members',type:'group',mark:'F',message:'Let us know what you decide.'},harbour:{name:'Harbour Café',kind:'Business · private chat',type:'business',mark:'HC',message:'Ask us about a table. Availability is not confirmed.'},place:{name:'Old harbour',kind:'Place · your personal note',type:'place',mark:'↗'}};
const state={view:'home',entity:null,time:'12:30',note:'Meet at Harbour Café on Saturday at 12:30?',noteEdited:false,drafts:{maya:'I will check with Family.'},scroll:{},recipient:null,review:null,receipts:[],returnView:'lens',origin:'open-intent',lensFrom:null,pendingSent:null};
const mark=id=>`<span class="mark ${people[id].type}" aria-hidden="true">${people[id].mark}</span>`;
function remember(){const node=document.querySelector('#content');if(node)state.scroll[state.view+(state.entity||'')]=node.scrollTop;const draft=document.querySelector('#reply');if(draft)state.drafts[state.entity]=draft.value;}
function bar(title,subtitle,back='Back to your connections'){return `<header class="bar"><button class="back" id="back" aria-label="${back}">‹</button><div><h2>${title}</h2><p class="small">${subtitle}</p></div></header>`;}
function paths(){return Object.keys(people).map(id=>`<button class="path" id="path-${id}" data-entity="${id}">${mark(id)}<span><span class="arrow" aria-hidden="true">↗</span><strong>${people[id].name}</strong><small>${people[id].kind}</small></span></button>`).join('');}
function dock(){return `<div class="dock"><button class="dock-button" id="resume-intent"><span aria-hidden="true">↗</span><strong>Saturday · ${state.time}</strong><small>Your private thread · no shared audience</small></button></div>`;}
function render(focus){
 if(state.view==='home')app.innerHTML=`<div id="content" class="scroll"><div class="top"><strong>SimpleX</strong><span class="profile" aria-label="Illustrative profile mark A">A</span></div><h1>Your people.<br>Your life.</h1><div class="favourites">${['maya','family','harbour'].map(id=>`<button class="favourite" id="home-${id}" data-entity="${id}">${mark(id)}<strong>${people[id].name}</strong><small>${id==='maya'?'Person':id==='family'?'Group':'Business'}</small></button>`).join('')}</div><p class="section-label">A purpose you keep</p><button class="purpose-seed" id="open-intent"><small>PRIVATE THREAD · CREATED BY YOU</small><h2>Saturday.</h2><p>Three connections. One place.<br>No new group. No shared history.</p><div class="seed-object"><strong>${state.time}</strong><span>Harbour Café · your plan, not a booking</span></div></button><p class="section-label">Recent</p>${['maya','family'].map(id=>`<button class="recent" data-entity="${id}">${mark(id)}<span><strong>${people[id].name}</strong><small>${people[id].kind}</small><p>${people[id].message}</p></span></button>`).join('')}</div>`;
 else if(state.view==='lens')app.innerHTML=bar('Saturday.','Your private thread',state.lensFrom?'Back to '+people[state.lensFrom].name:'Back to your connections')+`<div id="content" class="scroll"><div class="lens-head"><div><span class="local-label">YOUR PLAN · NOT SHARED</span><h2>A day by the harbour.</h2></div></div><section class="plan" aria-label="Your local plan"><h2>${state.time}</h2><p class="plan-line">Harbour Café.</p><small>Saturday · suggestion, not a booking</small><div class="times" role="group" aria-label="Local time">${['11:00','12:30'].map(t=>`<button data-time="${t}" aria-pressed="${state.time===t}">${t}</button>`).join('')}</div></section><div class="paths" aria-label="Your routes, not a shared membership">${paths()}</div><p class="lens-footer">These are your routes. Nobody here sees this thread or one another’s messages.</p><details class="footnote"><summary>What is this thread?</summary><p>A fictional, manually organised purpose. No inference, AI monitoring, group membership or location tracking. Only your own note can be carried; message histories remain separate.</p></details></div><div class="dock"><button class="primary" id="carry" style="width:100%">Carry a detail ↗</button></div>`;
 else if(state.view==='chat'){
 const person=people[state.entity];app.innerHTML=bar(person.name,person.kind,state.returnView==='lens'?'Back to Saturday':'Back to your connections')+`<div id="content" class="scroll">${mark(state.entity)}<article class="message"><small>${person.name}</small><p>${person.message}</p></article>${state.entity==='maya'?'<article class="message own"><small>You · fictional earlier message</small><p>The harbour would be lovely.</p></article><article class="message"><small>Maya</small><p>Check with Family? I can do late morning.</p></article>':state.entity==='family'?'<article class="message"><small>Priya · in Family</small><p>After midday is easier for me.</p></article>':'<article class="message"><small>Harbour Café</small><p>Please tell us the time and how many people.</p></article>'}${state.entity==='family'?'<p class="footnote">Fixture members: you, Maya, Alex and Priya. Membership is not agreement to your plan.</p>':''}${state.receipts.filter(r=>r.to===state.entity).map(r=>`<article class="message receipt"><small>Simulated message · to ${person.name} as Austin</small><p>${escapeHtml(r.text)}</p><small>No delivery, agreement or booking implied.</small></article>`).join('')}</div><div class="composer"><label for="reply">Your separate draft · to ${state.entity==='family'?'Family’s four members':person.name} as Austin</label><textarea id="reply" rows="2">${escapeHtml(state.drafts[state.entity]||'')}</textarea></div>`+dock();
 }else if(state.view==='place')app.innerHTML=bar('Old harbour','Place · your personal note','Back to Saturday')+`<div id="content" class="scroll"><span class="local-label">SAVED BY YOU · NO LOCATION ACCESS</span><h2>A place to meet.</h2><svg class="map" viewBox="0 0 300 220" role="img" aria-label="Illustrative harbour diagram, not a navigable map"><rect width="300" height="220" fill="#edf3f7"/><path d="M0 0h190q-70 90-30 220H0" fill="#e8e0d3"/><path d="M0 170q100-80 170-30" fill="none" stroke="white" stroke-width="20"/><circle cx="155" cy="137" r="10" fill="#913e2b"/></svg><p>Beside the old harbour, near the café.</p><p class="footnote">Fictional note you saved. It does not show anyone’s current location or establish who will attend.</p></div>`+dock();
 else if(state.view==='carry')app.innerHTML=bar('Carry one detail.','Your note stays separate','Back to Saturday')+`<div id="content" class="scroll"><span class="local-label">CHOOSE WHO SEES THIS</span><h2>The purpose connects.<br>The audiences don’t.</h2><div class="destinations" role="group" aria-label="Recipient">${['maya','family','harbour'].map(id=>`<button data-recipient="${id}" aria-pressed="${state.recipient===id}">${people[id].name}</button>`).join('')}</div><label for="detail">Your own note</label><textarea id="detail" maxlength="500" rows="3">${escapeHtml(state.note)}</textarea><p class="footnote">No conversation history, sender identity or saved place note is attached. This is text you edit, not a forwarded source message.</p><div class="actions"><button id="cancel-carry">Cancel</button><button id="review-detail" class="primary" ${!state.recipient||!state.note.trim()?'disabled':''}>Review detail</button></div></div>`;
 else if(state.view==='review')app.innerHTML=bar('Review the crossing.','Client-owned review','Back to editing')+`<div id="content" class="scroll"><section class="review"><span class="local-label">ONLY THIS TEXT WILL BE SIMULATED</span><h2>To ${people[state.review.to].name}.</h2><p>As <strong>Austin</strong></p>${state.review.to==='family'?'<p class="small">Audience: you, Maya, Alex and Priya in the fixture.</p>':''}<blockquote>${escapeHtml(state.review.text)}</blockquote><p class="small">Your private thread, other drafts and histories stay here. This does not claim group agreement or a confirmed booking.</p><div class="actions"><button id="edit-detail">Edit</button><button class="primary" id="send-detail">Simulate message</button></div><button id="cancel-carry" class="carry">Cancel crossing</button></section></div>`;
 const content=document.querySelector('#content');if(content)content.scrollTop=state.scroll[state.view+(state.entity||'')]||0;
 if(focus){document.getElementById(focus)?.focus({preventScroll:true});document.getElementById(focus)?.scrollIntoView({block:'nearest'});}
}
function route(view,focus){history.pushState({view,entity:state.entity,returnView:state.returnView,lensFrom:state.lensFrom},'', '#'+view);state.view=view;render(focus);}
app.addEventListener('input',event=>{if(event.target.id==='reply')state.drafts[state.entity]=event.target.value;if(event.target.id==='detail'){state.note=event.target.value;state.noteEdited=true;document.querySelector('#review-detail').disabled=!state.recipient||!state.note.trim();}});
app.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;remember();history.replaceState({...history.state,returnFocus:button.id||'back'},'',location.href);
 if(button.id==='open-intent'){state.entity=null;state.lensFrom=null;state.origin='open-intent';route('lens','back');}
 else if(button.dataset.entity){remember();state.returnView=state.view==='home'?'home':'lens';state.origin=button.id||'open-intent';state.entity=button.dataset.entity;state.lensFrom=null;route(state.entity==='place'?'place':'chat','back');say('Opened '+people[state.entity].name+'. No content copied.');}
 else if(button.id==='resume-intent'){state.lensFrom=state.entity;route('lens','back');say('Your private purpose resumed. Nothing shared.');}
 else if(button.dataset.time){state.time=button.dataset.time;if(!state.noteEdited)state.note='Meet at Harbour Café on Saturday at '+state.time+'?';render();document.querySelector('[data-time="'+state.time+'"]').focus({preventScroll:true});say('Time changed only in your plan. Existing simulated messages are unchanged.');}
 else if(button.id==='carry'){state.recipient=null;state.review=null;route('carry','cancel-carry');say('Choose a recipient. Nothing leaves during preparation.');}
 else if(button.dataset.recipient){state.recipient=button.dataset.recipient;render();document.querySelector('[data-recipient="'+state.recipient+'"]').focus({preventScroll:true});}
 else if(button.id==='review-detail'){state.review={to:state.recipient,text:state.note.trim()};route('review','send-detail');say('Review the exact text, audience and identity.');}
 else if(button.id==='edit-detail'){history.back();}
 else if(button.id==='send-detail'){const r=state.review;if(!r)return;if(!state.receipts.some(x=>x.to===r.to&&x.text===r.text))state.receipts.push({...r});state.review=null;state.pendingSent=r.to;history.go(-2);}
 else if(button.id==='cancel-carry'){const steps=state.view==='review'?-2:-1;state.review=null;state.recipient=null;history.go(steps);}
 else if(button.id==='back'){history.back();}
});
app.addEventListener('keydown',event=>{if(event.key==='Escape'&&['carry','review'].includes(state.view)){event.preventDefault();document.getElementById('cancel-carry').click();}});
window.addEventListener('popstate',event=>{remember();const target=event.state||{view:'home',entity:null};state.view=target.view;state.entity=target.entity;state.returnView=target.returnView||'lens';state.lensFrom=target.lensFrom||null;if(state.view==='review'&&!state.review){state.view='lens';state.entity=null;history.replaceState({view:'lens',entity:null},'','#lens');}if(state.pendingSent){state.entity=state.pendingSent;state.pendingSent=null;state.returnView='lens';state.lensFrom=null;history.pushState({view:'chat',entity:state.entity,returnView:'lens',lensFrom:null},'','#chat');state.view='chat';render('resume-intent');say('One message simulated to '+people[state.entity].name+'. Nothing delivered.');}else{render(target.returnFocus||(state.view==='home'?'open-intent':'back'));say('Context restored. Drafts stay separate.');}});
history.replaceState({view:'home',entity:null},'',location.pathname+location.search);render();
