(()=>{'use strict';
const screens=[
['home','Your space','Private messages and public channels in one list, with explicit types and profile-scoped search.','Coordination: the centre helps you find a relationship without turning everyone into a node on a map.'],
['chat','Read & reply','Read, reply and open tools in the same relationship. Drafts survive moving between designs until the page reloads.','Local action: expand the thing you need and return without losing your words.'],
['photo','Share an image','Review one illustrative image and its audience before sending. Try a failed send and an explicit retry.','Local touch: attach a comment to the point that prompted it, while retaining the whole image.'],
['plan','Shape a plan','Turn a question into a private proposal. Sharing a version with Maya is a separate, explicit action.','Adaptable form: a conversation can contain a working object with a visible source. This is speculative.'],
['connect','Make a connection','Choose the profile to disclose, then create a demo invitation. A pending request is not an established connection.','Selective disclosure: show the intended identity before you expose a connection route.'],
['group','Choose who joins','Inspect a group invitation and role, then accept or decline. Joining does not confirm a plan.','A readable boundary: membership and agreement are different decisions.'],
['privacy','Control visibility','Keep local profiles separate and hide message previews. A work draft remains separate from personal conversations.','Selective visibility: quietness comes from deliberate control, not hidden or unpredictable actions.'],
['trust','Connection security','Review the comparison process from the relationship. A demonstration cannot establish cryptographic trust.','Trust is inspectable in context; a reassuring colour is never evidence of verification.'],
['email','Email, in context','Explore how an email could live beside chat while keeping its external transport and recipients explicit.','A future hypothesis: continuity must not blur the difference between email and a SimpleX conversation.']
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({profile:'personal',previews:true,filter:'all',search:'',active:'Maya',drafts:{},messages:{},photoCaption:'The little cove on the right?',photoStatus:'draft',photoFail:false,anchor:false,planTitle:'Saturday by the sea',planDay:'Saturday',planShared:null,invite:'none',incognito:false,inviteName:'',group:'pending',role:'member',groupDraft:'',groupMessages:[],mailDraft:'',mailSent:false,trustSeen:false});
let state=initial(),view='home';const scene=document.querySelector('#scene'),root=document.querySelector('.device');
const contacts={personal:[['Maya','Shall we go on Saturday?','I found a quiet place by the sea.','2'],['Coast Journal','A quieter route to the sea.','New field notes from the harbour.','1','channel'],['Family','Lunch on Sunday?','I can bring something.','3'],['Studio','New sketches are ready.','The second direction feels clearer.','1'],['Design Dispatch','Objects that adapt to their purpose.','Inside the latest material study.','','channel'],['Alex','See you next week.','Thanks for the photos.',''],['Book club','Chapter six this week.','Sunday works for me.','']],work:[['Design team','The review is ready.','Can we try the compact option?','2'],['Project notes','Keep the source visible.','Test the sharing boundary.','']]};
const key=()=>state.profile+':'+state.active;const btn=(text,action,kind='control',extra='')=>`<button class="${kind}" data-action="${action}" ${extra}>${text}</button>`;const link=(text,dest,kind='quiet')=>`<button class="${kind}" data-view="${dest}">${text}</button>`;const notice=(text,error=false)=>`<div class="notice${error?' error':''}">${text}</div>`;const meta=text=>`<span class="meta">${text}</span>`;
function frame(title,body,dock='',back='home'){
 const drafting=(view==='chat'&&!contacts[state.profile].some(c=>c[0]===state.active&&c[4]==='channel'))||(view==='group'&&state.group==='joined'&&state.role==='member');
 scene.dataset.layout=drafting?'conversation':view==='home'?'index':view==='photo'?'media':'decision';
 return `<div class="screen-head">${view!=='home'?`<button class="back" data-back="${back}" aria-label="Back">‹</button>`:'<a class="back mobile-exit" href="experience.html#home" aria-label="Return to the design story">‹</a>'}<div class="head-title"><h2 tabindex="-1">${title}</h2><span class="meta" id="profile-label">${state.profile==='personal'?'Personal':'Work'}</span></div>${view==='home'?'<button class="back" data-view="connect" aria-label="New connection">+</button>':''}</div><div class="screen-body" tabindex="0" aria-label="${title.replace(/<[^>]*>/g,'')} content">${body}</div>${dock?`<div class="dock">${dock}</div>`:''}`;
}
const disclosure=(label,body)=>`<details class="source-detail"><summary>${label}</summary><p>${body}</p></details>`;
const drawing=()=>`<svg viewBox="0 0 600 380" role="img" aria-label="Illustrated coast with a small cove on the right" preserveAspectRatio="xMidYMid slice"><rect width="600" height="380" fill="#c4e6ea"/><path d="M0 135 Q180 100 600 160V380H0Z" fill="#1687a2"/><path d="M0 230 Q150 130 260 235T600 245V380H0Z" fill="#0b657a"/><path d="M420 110 Q310 180 400 250 Q435 305 600 270V0H550Z" fill="#d5ceb5"/><path d="M460 125 Q345 190 430 253 Q460 280 600 245" fill="none" stroke="#f3f6dc" stroke-width="13"/><path d="M0 330 Q150 245 310 350L370 380H0Z" fill="#354e45"/><circle cx="117" cy="67" r="28" fill="#f3f5d8"/></svg>`;
const photo=anchor=>`<figure class="photo"><div class="image-canvas">${drawing()}${anchor?btn('1','anchor','point','aria-label="Toggle comment on the cove" aria-pressed="'+state.anchor+'"'):''}</div><figcaption>Coast illustration · sample media</figcaption></figure>`;
function home(){const all=contacts[state.profile];const rows=all.filter(c=>(state.filter==='all'||state.filter==='unread'&&c[3]||state.filter==='private'&&c[4]!=='channel'||state.filter==='channel'&&c[4]==='channel')&&(!state.search||c.slice(0,state.previews?3:1).join(' ').toLowerCase().includes(state.search.toLowerCase())));return frame('Your space',`<p class="meta">${all.length} entries · private + channels</p><label class="sr-only" for="search">Search current profile</label><input class="search" id="search" placeholder="Find a conversation" value="${esc(state.search)}"><div class="chips">${btn('All','all','chip',`aria-pressed="${state.filter==='all'}"`)}${btn('Private','private','chip',`aria-pressed="${state.filter==='private'}"`)}${btn('Channels','channel','chip',`aria-pressed="${state.filter==='channel'}"`)}${btn('Unread','unread','chip',`aria-pressed="${state.filter==='unread'}"`)}</div><div id="conversation-list">${rows.map(c=>`<button class="list-item ${c[4]==='channel'?'channel-row':'private-row'}" data-contact="${esc(c[0])}"><span class="entry-kind">${c[4]==='channel'?'▤ Channel · public':'○ Private'}</span><span class="name">${esc(c[0])}<span class="badge">${c[3]?c[3]+' unread':''}</span></span><span class="preview">${state.previews?`${esc(c[1])}<br>${esc(c[2])}`:'Message previews hidden'}</span>${state.previews&&state.drafts[state.profile+':'+c[0]]?'<span class="badge">Draft kept</span>':''}</button>`).join('')||'<p class="empty">No conversations match. Try another name.</p>'}</div>`,`<div class="tools">${link('Visibility','privacy')}${link('Group invitation','group')}${link('Email study','email')}</div>`);}
function chat(){const channel=contacts[state.profile].find(c=>c[0]===state.active&&c[4]==='channel');if(channel)return frame(esc(channel[0]),`<p class="entry-kind">▤ Public channel · sample subscription</p><div class="sheet"><p class="overline">Published by ${esc(channel[0])}</p><h3>${esc(channel[1])}</h3><p>${esc(channel[2])}</p></div><div class="bound"><strong>Audience: channel readers</strong><p>No private messages are included in this publication.</p></div>`,`<p>Reading mode · comments off in this sample.</p>${link('Return to the menu','home','control')}`);const c=contacts[state.profile].find(c=>c[0]===state.active)||contacts[state.profile][0];const msgs=state.messages[key()]||[];return frame(esc(state.active),`<div class="quote"><span class="meta">${esc(state.active)} · 10:24</span><p>${esc(c[1])}</p></div><div class="quote"><span class="meta">${esc(state.active)} · 10:25</span><p>${esc(c[2])}</p></div>${state.active==='Maya'&&state.profile==='personal'?`<div class="sheet"><span class="overline">From Maya’s question</span><h3>Saturday by the sea</h3>${link('Shape a private proposal ↗','plan')}</div>`:''}<div class="message-log">${msgs.map(m=>`<div class="outgoing">${esc(m)}<small>You · sent in simulation</small></div>`).join('')}</div>`,`<p>To ${esc(state.active)} · ${state.profile} profile</p><label class="sr-only" for="reply">Message to ${esc(state.active)}</label><div class="composer"><textarea id="reply" placeholder="Your reply…" maxlength="1000">${esc(state.drafts[key()]||'')}</textarea>${btn('↑','send','send',`aria-label="Send reply in simulation" ${!state.drafts[key()]?.trim()?'disabled':''}`)}</div><div class="tools">${state.active==='Maya'&&state.profile==='personal'?link('＋ Image','photo'):''}${link('Connection security','trust')}</div>`);}
function photoScreen(){const sent=state.photoStatus==='sent';return frame('Share an image',`<p class="meta">To Maya · 1 image</p>${photo(sent)}${sent?`${notice('Image and caption sent in simulation. No external delivery.')}<div class="quote"><span class="meta">Your caption</span><p>${esc(state.photoCaption||'No caption')}</p></div>${state.anchor?notice('Point 1 · The cove on the right. This is your local annotation; no reply from Maya is invented.'):''}`:`<label class="inline-label" for="caption">Caption · optional</label><textarea id="caption" maxlength="500">${esc(state.photoCaption)}</textarea>${disclosure('Image details','Coast illustration · sample media. No embedded location metadata.')}${state.photoStatus==='failed'?notice('Not sent. Your image and caption are still here. Retry sends this same selection.',true):''}`}`,sent?link('Return to Maya','chat','control'):`<p>Only Maya receives this image and caption.</p>${btn(state.photoStatus==='failed'?'Retry image':'Send image to Maya','send-photo')} ${btn('Cancel and return','cancel-photo','quiet')}`,'chat');}
const proposalTitle=()=>state.planTitle.trim()||'Untitled proposal';
const sameProposal=()=>state.planShared?.title===proposalTitle()&&state.planShared?.day===state.planDay;
function syncProposal(){const b=scene.querySelector('[data-action=share-plan]');if(b){b.disabled=sameProposal();b.textContent=sameProposal()?'This version is already shared':'Share this version · simulation';}}
function plan(){return frame('Your proposal',`<p class="meta">Maya’s question → your private draft</p><div class="sheet"><p class="overline">Your private draft</p><label class="sr-only" for="plan-title">Proposal title</label><input id="plan-title" value="${esc(state.planTitle)}" maxlength="80"><label class="inline-label" for="plan-day">Proposed day</label><select id="plan-day" style="background:var(--pearl);color:var(--pearl-ink)"><option ${state.planDay==='Saturday'?'selected':''}>Saturday</option><option ${state.planDay==='Sunday'?'selected':''}>Sunday</option></select></div><details class="source-detail"><summary>Keep the source in view</summary><p>Maya: “Shall we go on Saturday?”</p></details><div class="bound"><strong>To Maya · title and day</strong><p>Your private draft stays separate from the shared version.</p></div>${state.planShared?notice(`Last shared: ${esc(state.planShared.title)} · ${state.planShared.day}. Maya has not confirmed.`):notice('Not shared · only you')}`,`<p>To Maya · title and proposed day</p>${btn(sameProposal()?'This version is already shared':'Share this version · simulation','share-plan','control',sameProposal()?'disabled':'')} ${link('Keep draft and return','chat')}`,'chat');}
function connect(){return frame('New connection',`<p class="meta">One-time invitation</p>${state.invite==='none'?`<div class="sheet"><p class="overline">Identity to be shown</p><h3>${state.incognito?'River Finch':'Austin'}</h3><p class="meta">${state.incognito?'Illustrative incognito name':'Your personal profile'}</p></div><label class="toggle">Use an incognito identity<input id="incognito" type="checkbox" ${state.incognito?'checked':''}></label>${disclosure('Invitation or contact address?','This invitation is single-use. A reusable contact address receives new requests and can be removed without breaking existing connections.')}`:`<div class="sheet"><p class="overline">${state.invite==='accepted'?'Connection accepted in simulation':'Demo invitation'}</p><h3>${esc(state.inviteName)}</h3><img class="qr" src="visuals/demo-qr.svg" alt="Demo-only QR, not a valid SimpleX invitation"><p class="meta">Demo QR · not a valid invitation</p></div>${notice(state.invite==='accepted'?'A fictional recipient accepted. No real connection was created.':'Pending · nobody has joined')}`}`,state.invite==='none'?btn('Create demo invitation','create-invite'):state.invite==='pending'?`${btn('Simulate recipient accepting','accept-invite')}${btn('Revoke invitation','revoke','quiet')}`:link('Return to your people','home','control'));}
function group(){const joined=state.group==='joined';return frame('Weekend circle',`<p class="meta">${joined?'Joined in simulation':'Invitation from Maya'} · personal profile</p><div class="sheet"><p class="overline">A separate conversation</p><h3>Make plans together.</h3><p class="meta">Private messages with Maya stay outside.</p></div><div class="member"><span>Maya</span><small>Owner</small></div><div class="member"><span>Alex</span><small>Member</small></div><div class="member"><span>You</span><small>${joined?state.role:state.group==='declined'?'Declined':'Not joined'}</small></div>${!joined?`<p class="meta role-summary">Offered role: ${state.role==='member'?'Member · can send':'Observer · can read'}</p>`:''}${notice(joined?'Membership is separate from agreeing to Saturday’s plan.':state.group==='declined'?'Invitation declined. No membership was created.':'Joining adds you to this group, not to a confirmed plan.')}<div class="message-log">${state.groupMessages.map(m=>`<div class="outgoing">${esc(m)}<small>To Weekend circle · simulated</small></div>`).join('')}</div>`,joined?`${state.role==='member'?`<label class="sr-only" for="group-reply">Message to Weekend circle</label><div class="composer"><textarea id="group-reply" placeholder="Write to the group…" maxlength="1000">${esc(state.groupDraft)}</textarea>${btn('↑','send-group','send',`aria-label="Send group message in simulation" ${!state.groupDraft.trim()?'disabled':''}`)}</div>`:'<p>Observer role · sending is unavailable.</p>'}${btn('Leave group','leave','quiet')}`:state.group==='declined'?btn('Reset invitation scenario','reset-group'): `${btn('Join group · simulation','join')}${btn('Decline invitation','decline','quiet')}`);}
function privacy(){return frame('Visibility',`<div class="chips">${btn('Personal','personal','chip',`aria-pressed="${state.profile==='personal'}"`)}${btn('Work','work','chip',`aria-pressed="${state.profile==='work'}"`)}</div><div class="sheet"><p class="overline">Active context</p><h3>${state.profile==='personal'?'Personal relationships':'Work conversations'}</h3><p class="meta">${contacts[state.profile].length} sample entries. Search stays within this profile.</p></div><label class="toggle">Show message previews<input id="previews" type="checkbox" ${state.previews?'checked':''}></label>${disclosure('What does hiding previews change?','The list keeps names and unread counts. Message text and draft markers are hidden. This is visual concealment, not authentication.')}<div class="bound"><strong>Profiles stay separate</strong><p>Search and drafts belong to the active profile.</p></div>${disclosure('Hidden profiles and locking','Hidden profiles require the native password flow. This study has no authentication and contains no hidden-profile data.')}`,link('Return to this profile','home','control'));}
function trust(){return frame('Connection security',`<p class="meta">Your relationship with ${esc(state.active)}</p><div class="sheet"><p class="overline">Comparison status</p><h3>Not verified here.</h3><p class="meta">No real security code is available in this study.</p></div><div class="quote"><p>Compare through another trusted channel.</p><span class="meta">Both people must compare the connection security code.</span></div>${disclosure('How comparison works','Open the contact’s connection security code and compare with the same code on their device, using another trusted channel. An invitation QR starts a connection; it does not verify this code.')}${state.trustSeen?notice('Review recorded locally. Verification status remains unchanged.'):''}`,`${btn('I reviewed the process','review-trust')}${link('Back to the conversation','chat')}`,'chat');}
function email(){return frame('Saturday’s booking',`<div class="sheet"><p class="overline">Email · external transport</p><p class="meta">From: reservations@example.com<br>To: austin@example.com</p><div class="seam"></div><p>We have a table available at 12:30.</p></div>${disclosure('Who can see this email?','From reservations@example.com to austin@example.com. It is not shared with Maya or the group and does not inherit the security properties of a SimpleX conversation.')}${state.mailSent?notice('Email send simulated. No external delivery.'):''}`,`<p>Email reply to reservations@example.com</p><label class="sr-only" for="email-reply">Email reply</label><div class="composer"><textarea id="email-reply" placeholder="Reply by email…" maxlength="1000">${esc(state.mailDraft)}</textarea>${btn('↑','send-email','send',`aria-label="Send email in simulation" ${!state.mailDraft.trim()?'disabled':''}`)}</div>`);}
const builders={home,chat,photo:photoScreen,plan,connect,group,privacy,trust,email};
function say(t){document.querySelector('#announcement').textContent=t;}
function render(focus=false){scene.innerHTML=builders[view]();document.querySelector('#profile-label').textContent=state.profile==='personal'?'Personal':'Work';const controls=document.querySelector('#scenario-controls');controls.innerHTML=view==='photo'?`<label>Study scenario: fail first image send<input id="photo-fail" type="checkbox" ${state.photoFail?'checked':''}></label>`:view==='group'&&state.group!=='joined'?`<label for="role">Study scenario: offered role</label><select id="role"><option value="member" ${state.role==='member'?'selected':''}>Member · can send</option><option value="observer" ${state.role==='observer'?'selected':''}>Observer · can read</option></select>`:'';const spec=screens.find(s=>s[0]===view);document.querySelector('#stage-description').textContent=spec[2];document.querySelector('#design-rationale').textContent=spec[3];document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.screen===view)));if(scene.dataset.layout==='conversation'){const history=scene.querySelector('.screen-body');history.scrollTop=history.scrollHeight;}if(focus)scene.querySelector('h2').focus({preventScroll:true});}
// History contains route context, never message or draft text. Reset invalidates old entries.
let journey=Date.now();
function routeContext(){return {study:true,journey,view,profile:state.profile,active:state.active,search:state.search,filter:state.filter,scroll:scene.querySelector('.screen-body')?.scrollTop||0,previous:history.state?.journey===journey?history.state.previous:null};}
function saveRoute(){history.replaceState(routeContext(),'','#'+view);}
function go(v,replace=false,contact=null){
 if(!builders[v])return;
 const previous=replace?null:view;saveRoute();if(contact)state.active=contact;
 if(['photo','plan','connect','group','email'].includes(v)){state.profile='personal';if(['photo','plan'].includes(v))state.active='Maya';}
 view=v;const entry={...routeContext(),view:v,previous,scroll:0};
 history[replace?'replaceState':'pushState'](entry,'','#'+v);render(true);say(screens.find(s=>s[0]===v)[1]);
}
function restoreRoute(){
 const v=location.hash.slice(1);if(!builders[v])return;
 const entry=history.state;
 if(entry?.study&&entry.journey===journey){state.profile=entry.profile;state.active=entry.active;state.search=entry.search;state.filter=entry.filter;view=v;render(true);scene.querySelector('.screen-body').scrollTop=entry.scroll||0;}
 else {view=v;render(true);saveRoute();}
 say(screens.find(s=>s[0]===v)[1]);
}
document.querySelector('#screen-nav').innerHTML=screens.map((s,i)=>`<button data-screen="${s[0]}" aria-pressed="false"><span>${String(i+1).padStart(2,'0')}</span>${s[1]}</button>`).join('');document.querySelector('#gallery').innerHTML=screens.map((s,i)=>`<a href="#${s[0]}" data-gallery="${s[0]}"><img src="visuals/previews/experience-${s[0]}.png" alt="${s[1]} mobile design" loading="lazy"><h3>${String(i+1).padStart(2,'0')} / ${s[1]}</h3><p>${s[2]}</p></a>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button,a[data-gallery]');if(!b)return;if(b.dataset.palette){root.dataset.palette=b.dataset.palette;document.querySelectorAll('button[data-palette]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));return;}if(b.dataset.gallery){e.preventDefault();go(b.dataset.gallery);document.querySelector('#experience').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});return;}if(b.dataset.back){if(history.state?.journey===journey&&history.state.previous)history.back();else go(b.dataset.back,true);return;}if(b.dataset.screen||b.dataset.view){go(b.dataset.screen||b.dataset.view);return;}if(b.dataset.contact){go('chat',false,b.dataset.contact);return;}const a=b.dataset.action;if(!a)return;
if(a==='reset'){state=initial();journey=Date.now();go('home',true);say('Study reset. All local drafts cleared.');return;}
if(['all','unread','private','channel'].includes(a))state.filter=a;
if(a==='send'){const d=(state.drafts[key()]||'').trim();if(!d)return;(state.messages[key()]??=[]).push(d);state.drafts[key()]='';}
if(a==='send-photo'){if(state.photoFail&&state.photoStatus!=='failed'){state.photoStatus='failed';}else{state.photoStatus='sent';(state.messages['personal:Maya']??=[]).push('Image shared · '+(state.photoCaption||'Coast illustration'));}}
if(a==='cancel-photo'){state.photoStatus='draft';go('chat');say('Image was not sent. Caption retained.');return;}
if(a==='anchor')state.anchor=!state.anchor;
if(a==='share-plan'){if(sameProposal())return;state.planTitle=proposalTitle();state.planShared={title:state.planTitle,day:state.planDay};(state.messages['personal:Maya']??=[]).push(`Proposal: ${state.planTitle} · ${state.planDay}. Awaiting Maya’s response.`);}
if(a==='create-invite'){state.invite='pending';state.inviteName=state.incognito?'River Finch':'Austin';}
if(a==='accept-invite')state.invite='accepted';if(a==='revoke')state.invite='none';
if(a==='join')state.group='joined';if(a==='decline')state.group='declined';if(a==='reset-group')state.group='pending';if(a==='leave'){state.group='declined';state.groupDraft='';state.groupMessages=[];}
if(a==='send-group'&&state.group==='joined'&&state.role==='member'&&state.groupDraft.trim()){state.groupMessages.push(state.groupDraft.trim());state.groupDraft='';}
if(a==='personal'||a==='work'){state.profile=a;state.active=contacts[a][0][0];state.search='';state.filter='all';}
if(a==='review-trust')state.trustSeen=true;
if(a==='send-email'&&state.mailDraft.trim()){state.mailSent=true;state.mailDraft='';}
render(true);if(['send','send-group','send-email'].includes(a))scene.querySelector('textarea')?.focus({preventScroll:true});say(({send:'Reply sent in simulation.','send-photo':state.photoStatus==='failed'?'Image not sent. Retry is available.':'Image sent in simulation.','share-plan':'This proposal version shared in simulation. Maya has not confirmed.',revoke:'Invitation revoked.',join:'Group joined in simulation.',decline:'Invitation declined.',leave:'Group left in simulation.'})[a]||'Study updated.');});
scene.addEventListener('input',e=>{const t=e.target;if(t.id==='reply'){state.drafts[key()]=t.value;scene.querySelector('[data-action=send]').disabled=!t.value.trim();}if(t.id==='group-reply'){state.groupDraft=t.value;scene.querySelector('[data-action=send-group]').disabled=!t.value.trim();}if(t.id==='email-reply'){state.mailDraft=t.value;scene.querySelector('[data-action=send-email]').disabled=!t.value.trim();}if(t.id==='caption')state.photoCaption=t.value;if(t.id==='plan-title'){state.planTitle=t.value;syncProposal();}if(t.id==='search'){state.search=t.value;const pos=t.selectionStart;render();const el=scene.querySelector('#search');el.focus();el.setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='incognito'){state.incognito=t.checked;render();scene.querySelector('#incognito').focus();}if(t.id==='previews'){state.previews=t.checked;say(state.previews?'Previews visible.':'Previews hidden.');}if(t.id==='photo-fail')state.photoFail=t.checked;if(t.id==='plan-day'){state.planDay=t.value;syncProposal();}if(t.id==='role'){state.role=t.value;render();document.querySelector('#role')?.focus();}});
if(new URLSearchParams(location.search).get('mobile')==='1')document.body.classList.add('mobile-study');const requested=location.hash.slice(1);view=builders[requested]?requested:'home';render();saveRoute();window.addEventListener('popstate',restoreRoute);window.addEventListener('hashchange',()=>{if(location.hash.slice(1)!==view)restoreRoute();});
})();
