const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
const fs=require('fs'),path=require('path'),http=require('http');
(async()=>{
 const root=process.cwd();const server=http.createServer((req,res)=>{try{const file=path.resolve(root,'.'+req.url.split('?')[0]);if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Missing');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH,headless:true});
 try{const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});page.setDefaultTimeout(5000);await page.emulateMedia({reducedMotion:'reduce'});const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
 fs.mkdirSync('studies/intent-captures',{recursive:true});const shot=name=>page.locator('.phone').screenshot({path:'studies/intent-captures/'+name+'.png'});
 await page.goto(`http://127.0.0.1:${server.address().port}/studies/intent.html?mobile=1`);
 check(await page.locator('.favourite').count()===3,'Home organised around three human relationships');await shot('01-home');await page.locator('#open-intent').click();check((await page.locator('.local-label').innerText()).includes('NOT SHARED'),'Purpose is explicitly private');check(await page.locator('.path').count()===4,'People group business and place have distinct routes');await shot('02-purpose');
 await page.locator('[data-time="11:00"]').click();check((await page.locator('.plan').innerText()).includes('11:00'),'Time changes locally');await page.locator('#path-maya').click();check(await page.locator('.bar h2').innerText()==='Maya','Only one conversation is open');await page.locator('#reply').fill('My original Maya draft.');await shot('03-maya');await page.locator('#resume-intent').click();check(await page.locator('#back').getAttribute('aria-label')==='Back to Maya','Resumed purpose names its source conversation');await page.locator('#back').click();await page.locator('#reply').waitFor();check(await page.locator('#reply').inputValue()==='My original Maya draft.','Purpose fold restores original draft');check(await page.locator('#resume-intent').evaluate(e=>e===document.activeElement),'Purpose fold restores dock focus');await page.locator('#back').click();await page.locator('#path-family').click();check(await page.locator('#reply').inputValue()==='','Family does not receive Maya draft');await page.locator('#reply').fill('Independent Family draft.');await page.locator('#back').click();await page.locator('#path-place').click();check(await page.locator('#reply').count()===0,'Place has no chat composer');check((await page.locator('#content').innerText()).includes('does not show anyone'),'Place never claims live location');await shot('04-place');await page.locator('#back').click();
 await page.locator('#carry').click();check(!(await page.locator('#review-detail').isEnabled()),'No recipient is preselected');await page.locator('[data-recipient="family"]').click();await page.locator('#detail').fill('Meet at Harbour Café on Saturday at 11:00?');await shot('05-carry');await page.locator('#review-detail').click();check((await page.locator('.review').innerText()).includes('Alex and Priya'),'Group review names exact fictional audience');check((await page.locator('.review').innerText()).includes('As Austin'),'Review names active identity');await shot('06-review');await page.locator('#cancel-carry').click();await page.locator('#carry').waitFor();await page.locator('#path-family').click();check(await page.locator('.receipt').count()===0,'Cancelled crossing produces no simulated message');check(await page.locator('#reply').inputValue()==='Independent Family draft.','Cancelled crossing preserves target draft');await page.locator('#back').click();await page.locator('#carry').click();await page.locator('[data-recipient="family"]').click();await page.locator('#review-detail').click();await page.locator('#send-detail').click();await page.locator('.receipt').waitFor();check(await page.locator('.receipt').count()===1,'Explicit review commits one simulated snapshot');check(await page.locator('#reply').inputValue()==='Independent Family draft.','Commit does not overwrite target draft');await shot('07-snapshot');await page.locator('#back').click();await page.locator('#carry').waitFor();check(await page.locator('#back').getAttribute('aria-label')==='Back to your connections','Commit returns to source purpose with correct Back destination');await page.locator('[data-time="12:30"]').click();await page.locator('#path-family').click();check((await page.locator('.receipt').innerText()).includes('11:00'),'Changing private plan does not mutate sent snapshot');await page.locator('#back').click();await page.locator('#path-maya').click();check(await page.locator('#reply').inputValue()==='My original Maya draft.','Maya draft survives whole purpose journey');await shot('08-return');await page.locator('#back').click();await page.locator('#carry').click();await page.locator('#cancel-carry').press('Escape');await page.locator('#carry').waitFor();check(await page.locator('#detail').count()===0,'Escape cancels preparation');await page.locator('#carry').click();check(await page.locator('#detail').inputValue()==='Meet at Harbour Café on Saturday at 11:00?','Changing time does not silently overwrite an edited personal note');await page.locator('#cancel-carry').click();await page.locator('#carry').waitFor();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Purpose fits '+width);check(await page.locator('#carry').evaluate(e=>{const b=e.getBoundingClientRect(),p=e.closest('.phone').getBoundingClientRect();return b.top>=p.top&&b.bottom<=p.bottom;}),'Carry action visible without scrolling at '+width);}
 check(await page.locator('.scroll').evaluate(e=>getComputedStyle(e).animationName==='none'),'Reduced motion removes unfold transition');
 check(await page.locator('button').evaluateAll(items=>items.every(e=>e.getBoundingClientRect().height>=44)),'Current purpose controls meet 44 CSS px height');
 const board=await browser.newPage({viewport:{width:1400,height:1300},deviceScaleFactor:1});await board.goto(`http://127.0.0.1:${server.address().port}/studies/intent-board.html`);await board.locator('.grid img').evaluateAll(items=>Promise.all(items.map(e=>e.decode())));await board.screenshot({path:'studies/intent-captures/concept-board.png'});check(await board.locator('.grid img').evaluateAll(items=>items.every(e=>e.complete&&e.naturalWidth>0)),'Four visual board images load');check(errors.length===0,'No JavaScript errors');fs.writeFileSync('docs/intent-check.json',JSON.stringify({date:new Date().toISOString(),method:'Headless Chrome; fictional inputs; no participant, native platform or physical phone validation',checks},null,2)+'\n');console.log('PASS',checks.length,'thread of intent checks');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
